
database: /home/bvolkel/HF/MachineLearningHEP/machine_learning_hep/data/data_prod_20200304/database_ml_parameters_LcpK0spp_0304.yml

data_or_mc: mc

query_all: "is_ev_rej == 0"
#use_mass_window: false
#use_ml_selection: false

analysis: MBvspt_perc_v0m

distribution: n_tracklets

x_range:
    - 100
    - 0
    - 100

out_file: n_tracklets_MB_Lc_mc.root
